[build]
  command = "npx @11ty/eleventy"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self';"

[[redirects]]
  from = "/api/goatcounter"
  to = "https://229988.goatcounter.com/api/v0/stats/total"
  status = 200
  force = true
