name: Optimize Images

on:
  push:
    branches:
      - main
    paths:
      - 'src/Foto/**' # Путь к изображениям
  pull_request:
    branches:
      - main

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Optimize images
        run: |
          mkdir -p optimized-images
          find src/Foto/Galeri -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.webp" \) -exec mogrify -resize 50% -quality 80 -format webp -path optimized-images {} \;

      - name: Commit optimized images
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add optimized-images/
          git commit -m "Optimized images" || echo "No changes to commit"
          git push origin main